# QC plots
## Total read counts per sample
This reads per sample plot shows the total read counts (raw and normalized) for each sample. Bar colours represent experimental condition.
```\{r readCountPlot, fig.width={$rc_fig_width}, fig.height={$rc_fig_height}\}
plotReadCounts(dds, resultsDir)
```

## Null count percentage per sample
This null count percentage per sample plot shows the percentage of genes which have no counts (raw and normalized) for each sample. Bar colours represent experimental condition.
```\{r nullCountPlot, fig.width={$rc_fig_width}, fig.height={$rc_fig_height}\}
plotNullCounts(dds, resultsDir)
```

## Sample-to-sample distances
The sample-to-sample distance plot gives an overview of how the samples cluster based on their euclidean distance using the regularized log transformed count data.
```\{r plotSampleDistances, results="hide", fig.keep="all", warnings = FALSE, fig.width={$sd_fig_width}, fig.height={$sd_fig_height}\}
plotSampleDistances(dds, resultsDir)
```

##Principal component analysis (PCA)
### PCA plot
The Principal Component Analysis (PCA) plot shows the first two principal components which explain the variability in the data using the regularized log count data.  
```\{r pcaPlot, warning=FALSE, fig.width={$pca_fig_width}, fig.height={$pca_fig_height}\}
pc_list <- getPrincipalComponents(dds)
pcaPlot(pc_list,resultsDir)
```

### PC scree plot
The principal components (PC) scree plot shows the percentage contribution of each PC. 
```\{r pcaScreePlot, warning=FALSE, fig.width={$pcs_fig_width}, fig.height={$pcs_fig_height}\}
pcaScreePlot(pc_list,resultsDir)
```

### PC summary
The PC summary shows the percentage contribution (bars in scree plot) and cumulative total (points in scree plot) for each PC.
```\{r pcaSummary, warning=FALSE\}
pcaSummary(pc_list)
```

##Cook's distances
Cook's distance is a measure of how much a single sample is influencing the fitted coefficients for a gene. A large value of Cook's distance is intended to indicate an outlier count. 
```\{r plotCooks, results="hide", fig.keep="all", warning=FALSE, comment=FALSE, fig.width={$cd_fig_width}, fig.height={$cd_fig_height}\}
plotCooks(dds,resultsDir)
```

##Density plot
The density plot shows the distribution of normalised read counts per sample.
```\{r plotDensity, results="hide", fig.keep="all", comment=FALSE, warning = FALSE, fig.width={$dens_fig_width}, fig.height={$dens_fig_height}\}
plotDensity(dds,resultsDir)
```

##Dispersion plot
The dispersion estimate plot shows the gene-wise estimates (black), fitted values (red) and final maximum a posteriori estimates used in testing (blue).
```\{r plotDispersionEstimates, results="hide", fig.keep="all", warning = FALSE, fig.width={$disp_fig_width}, fig.height={$disp_fig_height}\}
plotDispersionEstimates(dds, resultsDir)
```